// <auto-generated />
using System;
using APIStarWar.InMemory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIStarWar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("APIStarWar.Models.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04009b4d-35cd-488b-a0fb-39a220bd2ffe"),
                            Created = new DateTime(2014, 12, 10, 14, 23, 31, 880, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 19, 49, 45, 256, DateTimeKind.Utc),
                            EpisodeId = 4,
                            FilmId = 1,
                            OpeningCrawl = "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
                            Producer = "Gary Kurtz, Rick McCallum",
                            Title = "A New Hope",
                            Url = "https://swapi.dev/api/films/1/"
                        },
                        new
                        {
                            Id = new Guid("c20783ca-68d3-48af-88be-8df06408e5ca"),
                            Created = new DateTime(2014, 12, 12, 11, 26, 24, 656, DateTimeKind.Utc),
                            Director = "Irvin Kershner",
                            Edited = new DateTime(2014, 12, 15, 13, 7, 53, 386, DateTimeKind.Utc),
                            EpisodeId = 5,
                            FilmId = 2,
                            OpeningCrawl = "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....",
                            Producer = "Gary Kurtz, Rick McCallum",
                            Title = "The Empire Strikes Back",
                            Url = "https://swapi.dev/api/films/2/"
                        },
                        new
                        {
                            Id = new Guid("cc5cd68c-2287-4048-ae3e-37fccccbae53"),
                            Created = new DateTime(2014, 12, 18, 10, 39, 33, 255, DateTimeKind.Utc),
                            Director = "Richard Marquand",
                            Edited = new DateTime(2014, 12, 20, 9, 48, 37, 462, DateTimeKind.Utc),
                            EpisodeId = 6,
                            FilmId = 3,
                            OpeningCrawl = "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
                            Producer = "Howard G. Kazanjian, George Lucas, Rick McCallum",
                            Title = "Return of the Jedi",
                            Url = "https://swapi.dev/api/films/3/"
                        },
                        new
                        {
                            Id = new Guid("465ebd3d-86eb-4ea4-a634-adfb8147f4dc"),
                            Created = new DateTime(2014, 12, 19, 16, 52, 55, 740, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 10, 54, 7, 216, DateTimeKind.Utc),
                            EpisodeId = 1,
                            FilmId = 4,
                            OpeningCrawl = "Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
                            Producer = "Rick McCallum",
                            Title = "The Phantom Menace",
                            Url = "https://swapi.dev/api/films/4/"
                        },
                        new
                        {
                            Id = new Guid("6c4797fa-c2a5-4cb4-b55d-009620baae33"),
                            Created = new DateTime(2014, 12, 20, 10, 57, 57, 886, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 20, 18, 48, 516, DateTimeKind.Utc),
                            EpisodeId = 2,
                            FilmId = 5,
                            OpeningCrawl = "There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....",
                            Producer = "Rick McCallum",
                            Title = "Attack of the Clones",
                            Url = "https://swapi.dev/api/films/5/"
                        },
                        new
                        {
                            Id = new Guid("e2f690e3-e9b3-4e5e-a25b-d6833a356426"),
                            Created = new DateTime(2014, 12, 20, 18, 49, 38, 403, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 20, 47, 52, 73, DateTimeKind.Utc),
                            EpisodeId = 3,
                            FilmId = 6,
                            OpeningCrawl = "War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....",
                            Producer = "Rick McCallum",
                            Title = "Revenge of the Sith",
                            Url = "https://swapi.dev/api/films/6/"
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.People", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthYear")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homeworld")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeopleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peoples");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b19eace-13bb-403c-ab0a-70ff2bc441e3"),
                            BirthYear = "19BBY",
                            Created = new DateTime(2014, 12, 9, 13, 50, 51, 644, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 56, 891, DateTimeKind.Utc),
                            EyeColor = "blue",
                            Gender = "male",
                            HairColor = "blond",
                            Height = "172",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "77",
                            Name = "Luke Skywalker",
                            PeopleId = 1,
                            SkinColor = "fair",
                            Url = "https://swapi.dev/api/people/1/"
                        },
                        new
                        {
                            Id = new Guid("c8cbdfa1-f3d6-4489-9c00-90f2b8c1c3ad"),
                            BirthYear = "112BBY",
                            Created = new DateTime(2014, 12, 10, 15, 10, 51, 357, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 309, DateTimeKind.Utc),
                            EyeColor = "yellow",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "167",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "75",
                            Name = "C-3PO",
                            PeopleId = 2,
                            SkinColor = "gold",
                            Url = "https://swapi.dev/api/people/2/"
                        },
                        new
                        {
                            Id = new Guid("35563a5d-f8e1-4e48-b543-84bafae1f929"),
                            BirthYear = "33BBY",
                            Created = new DateTime(2014, 12, 10, 15, 11, 50, 376, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 311, DateTimeKind.Utc),
                            EyeColor = "red",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "96",
                            Homeworld = "https://swapi.dev/api/planets/8/",
                            Mass = "32",
                            Name = "R2-D2",
                            PeopleId = 3,
                            SkinColor = "white, blue",
                            Url = "https://swapi.dev/api/people/3/"
                        },
                        new
                        {
                            Id = new Guid("3fa33eca-6095-4abe-b86a-409688aec876"),
                            BirthYear = "41.9BBY",
                            Created = new DateTime(2014, 12, 10, 15, 18, 20, 704, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 313, DateTimeKind.Utc),
                            EyeColor = "yellow",
                            Gender = "male",
                            HairColor = "none",
                            Height = "202",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "136",
                            Name = "Darth Vader",
                            PeopleId = 4,
                            SkinColor = "white",
                            Url = "https://swapi.dev/api/people/4/"
                        },
                        new
                        {
                            Id = new Guid("9a80b755-9732-4e26-ad75-7fdae5624c95"),
                            BirthYear = "19BBY",
                            Created = new DateTime(2014, 12, 10, 15, 20, 9, 791, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 315, DateTimeKind.Utc),
                            EyeColor = "brown",
                            Gender = "female",
                            HairColor = "brown",
                            Height = "150",
                            Homeworld = "https://swapi.dev/api/planets/2/",
                            Mass = "49",
                            Name = "Leia Organa",
                            PeopleId = 5,
                            SkinColor = "light",
                            Url = "https://swapi.dev/api/people/5/"
                        },
                        new
                        {
                            Id = new Guid("e98297ef-6935-4f28-8179-2ef93aeda458"),
                            BirthYear = "52BBY",
                            Created = new DateTime(2014, 12, 10, 15, 52, 14, 24, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 317, DateTimeKind.Utc),
                            EyeColor = "blue",
                            Gender = "male",
                            HairColor = "brown, grey",
                            Height = "178",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "120",
                            Name = "Owen Lars",
                            PeopleId = 6,
                            SkinColor = "light",
                            Url = "https://swapi.dev/api/people/6/"
                        },
                        new
                        {
                            Id = new Guid("69335ade-3332-4dd2-9b67-28088c182668"),
                            BirthYear = "47BBY",
                            Created = new DateTime(2014, 12, 10, 15, 53, 41, 121, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 319, DateTimeKind.Utc),
                            EyeColor = "blue",
                            Gender = "female",
                            HairColor = "brown",
                            Height = "165",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "75",
                            Name = "Beru Whitesun lars",
                            PeopleId = 7,
                            SkinColor = "light",
                            Url = "https://swapi.dev/api/people/7/"
                        },
                        new
                        {
                            Id = new Guid("cb464128-84ed-4cc6-9faa-b5e2f4855009"),
                            BirthYear = "unknown",
                            Created = new DateTime(2014, 12, 10, 15, 57, 50, 959, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 321, DateTimeKind.Utc),
                            EyeColor = "red",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "97",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "32",
                            Name = "R5-D4",
                            PeopleId = 8,
                            SkinColor = "white, red",
                            Url = "https://swapi.dev/api/people/8/"
                        },
                        new
                        {
                            Id = new Guid("3cf2f0f9-2b98-4ffc-ac88-fe2d5443b72c"),
                            BirthYear = "24BBY",
                            Created = new DateTime(2014, 12, 10, 15, 59, 50, 509, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 323, DateTimeKind.Utc),
                            EyeColor = "brown",
                            Gender = "male",
                            HairColor = "black",
                            Height = "183",
                            Homeworld = "https://swapi.dev/api/planets/1/",
                            Mass = "84",
                            Name = "Biggs Darklighter",
                            PeopleId = 9,
                            SkinColor = "light",
                            Url = "https://swapi.dev/api/people/9/"
                        },
                        new
                        {
                            Id = new Guid("22d4dff7-cab7-4837-ad60-c661c05af345"),
                            BirthYear = "57BBY",
                            Created = new DateTime(2014, 12, 10, 16, 16, 29, 192, DateTimeKind.Utc),
                            Edited = new DateTime(2014, 12, 20, 21, 17, 50, 325, DateTimeKind.Utc),
                            EyeColor = "blue-gray",
                            Gender = "male",
                            HairColor = "auburn, white",
                            Height = "182",
                            Homeworld = "https://swapi.dev/api/planets/20/",
                            Mass = "77",
                            Name = "Obi-Wan Kenobi",
                            PeopleId = 10,
                            SkinColor = "fair",
                            Url = "https://swapi.dev/api/people/10/"
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Climate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrbitalPeriod")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Population")
                        .HasColumnType("TEXT");

                    b.Property<string>("RotationPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceWater")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terrain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64f607a5-0d6b-4890-bc5f-531569810a4a"),
                            Climate = "arid",
                            Created = new DateTime(2014, 12, 9, 13, 50, 49, 641, DateTimeKind.Utc),
                            Diameter = "10465",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 411, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Tatooine",
                            OrbitalPeriod = "304",
                            PlanetId = 1,
                            Population = "10",
                            RotationPeriod = "23",
                            SurfaceWater = "1",
                            Terrain = "desert",
                            Url = "https://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            Id = new Guid("04c4b689-f1ee-4d4a-bd6c-fd6e13a2b15f"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 35, 48, 479, DateTimeKind.Utc),
                            Diameter = "12500",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 420, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Alderaan",
                            OrbitalPeriod = "364",
                            PlanetId = 2,
                            Population = "3",
                            RotationPeriod = "24",
                            SurfaceWater = "40",
                            Terrain = "grasslands, mountains",
                            Url = "https://swapi.dev/api/planets/2/"
                        },
                        new
                        {
                            Id = new Guid("87b36881-0241-4984-a9b4-87f6f3a4548d"),
                            Climate = "temperate, tropical",
                            Created = new DateTime(2014, 12, 10, 11, 37, 19, 144, DateTimeKind.Utc),
                            Diameter = "10200",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 421, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Yavin IV",
                            OrbitalPeriod = "4818",
                            PlanetId = 3,
                            Population = "0",
                            RotationPeriod = "24",
                            SurfaceWater = "8",
                            Terrain = "jungle, rainforests",
                            Url = "https://swapi.dev/api/planets/3/"
                        },
                        new
                        {
                            Id = new Guid("426524f3-9a72-4bb1-a54a-3637155de384"),
                            Climate = "frozen",
                            Created = new DateTime(2014, 12, 10, 11, 39, 13, 934, DateTimeKind.Utc),
                            Diameter = "7200",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 423, DateTimeKind.Utc),
                            Gravity = "1.1 standard",
                            Name = "Hoth",
                            OrbitalPeriod = "549",
                            PlanetId = 4,
                            Population = "0",
                            RotationPeriod = "23",
                            SurfaceWater = "100",
                            Terrain = "tundra, ice caves, mountain ranges",
                            Url = "https://swapi.dev/api/planets/4/"
                        },
                        new
                        {
                            Id = new Guid("24e8e561-4958-4ce7-b3ef-bdb0637b59c5"),
                            Climate = "murky",
                            Created = new DateTime(2014, 12, 10, 11, 42, 22, 590, DateTimeKind.Utc),
                            Diameter = "8900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 425, DateTimeKind.Utc),
                            Gravity = "N/A",
                            Name = "Dagobah",
                            OrbitalPeriod = "341",
                            PlanetId = 5,
                            Population = "0",
                            RotationPeriod = "23",
                            SurfaceWater = "8",
                            Terrain = "swamp, jungles",
                            Url = "https://swapi.dev/api/planets/5/"
                        },
                        new
                        {
                            Id = new Guid("3206e29e-f660-4bc1-ac9f-7bb88ec32d87"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 43, 55, 240, DateTimeKind.Utc),
                            Diameter = "118000",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 427, DateTimeKind.Utc),
                            Gravity = "1.5 (surface), 1 standard (Cloud City)",
                            Name = "Bespin",
                            OrbitalPeriod = "5110",
                            PlanetId = 6,
                            Population = "1",
                            RotationPeriod = "12",
                            SurfaceWater = "0",
                            Terrain = "gas giant",
                            Url = "https://swapi.dev/api/planets/6/"
                        },
                        new
                        {
                            Id = new Guid("3d85e8da-4d4a-4926-a1c7-16ea50f52802"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 50, 29, 349, DateTimeKind.Utc),
                            Diameter = "4900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 429, DateTimeKind.Utc),
                            Gravity = "0.85 standard",
                            Name = "Endor",
                            OrbitalPeriod = "402",
                            PlanetId = 7,
                            Population = "1",
                            RotationPeriod = "18",
                            SurfaceWater = "8",
                            Terrain = "forests, mountains, lakes",
                            Url = "https://swapi.dev/api/planets/7/"
                        },
                        new
                        {
                            Id = new Guid("aff71f2d-2cf6-4b86-8246-c649ab6c37d9"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 52, 31, 66, DateTimeKind.Utc),
                            Diameter = "12120",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 430, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Naboo",
                            OrbitalPeriod = "312",
                            PlanetId = 8,
                            Population = "11",
                            RotationPeriod = "26",
                            SurfaceWater = "12",
                            Terrain = "grassy hills, swamps, forests, mountains",
                            Url = "https://swapi.dev/api/planets/8/"
                        },
                        new
                        {
                            Id = new Guid("091dc879-cb26-4db7-ac7d-24571246f8b3"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 54, 13, 921, DateTimeKind.Utc),
                            Diameter = "12240",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 432, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Coruscant",
                            OrbitalPeriod = "368",
                            PlanetId = 9,
                            Population = "3",
                            RotationPeriod = "24",
                            SurfaceWater = "unknown",
                            Terrain = "cityscape, mountains",
                            Url = "https://swapi.dev/api/planets/9/"
                        },
                        new
                        {
                            Id = new Guid("d8914c66-5ad5-41a0-8743-f89e5c0ba572"),
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 12, 45, 6, 577, DateTimeKind.Utc),
                            Diameter = "19720",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 434, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Kamino",
                            OrbitalPeriod = "463",
                            PlanetId = 10,
                            Population = "3",
                            RotationPeriod = "27",
                            SurfaceWater = "100",
                            Terrain = "ocean",
                            Url = "https://swapi.dev/api/planets/10/"
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.Specie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageHeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageLifespan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColors")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homeworld")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinColors")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = new Guid("794d3556-5fcc-4196-973a-7e46b37264fe"),
                            AverageHeight = "180",
                            AverageLifespan = "120",
                            Created = new DateTime(2014, 12, 10, 13, 52, 11, 567, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 136, DateTimeKind.Utc),
                            EyeColors = "brown, blue, green, hazel, grey, amber",
                            HairColors = "blonde, brown, black, red",
                            Homeworld = "https://swapi.dev/api/planets/9/",
                            Language = "Galactic Basic",
                            Name = "Human",
                            SkinColors = "caucasian, black, asian, hispanic",
                            SpecieId = 1,
                            Url = "https://swapi.dev/api/species/1/"
                        },
                        new
                        {
                            Id = new Guid("ef5eca59-eb49-4dba-9497-ccf48a1f093a"),
                            AverageHeight = "n/a",
                            AverageLifespan = "indefinite",
                            Created = new DateTime(2014, 12, 10, 15, 16, 16, 259, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 139, DateTimeKind.Utc),
                            EyeColors = "n/a",
                            HairColors = "n/a",
                            Language = "n/a",
                            Name = "Droid",
                            SkinColors = "n/a",
                            SpecieId = 2,
                            Url = "https://swapi.dev/api/species/2/"
                        },
                        new
                        {
                            Id = new Guid("b334dbd6-5508-46f7-ab7e-4dd032c84235"),
                            AverageHeight = "210",
                            AverageLifespan = "400",
                            Created = new DateTime(2014, 12, 10, 16, 44, 31, 486, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 142, DateTimeKind.Utc),
                            EyeColors = "blue, green, yellow, brown, golden, red",
                            HairColors = "black, brown",
                            Homeworld = "https://swapi.dev/api/planets/14/",
                            Language = "Shyriiwook",
                            Name = "Wookie",
                            SkinColors = "gray",
                            SpecieId = 3,
                            Url = "https://swapi.dev/api/species/3/"
                        },
                        new
                        {
                            Id = new Guid("39685f34-5d0c-4a4c-b185-d7e544dc535b"),
                            AverageHeight = "170",
                            AverageLifespan = "unknown",
                            Created = new DateTime(2014, 12, 10, 17, 5, 26, 471, DateTimeKind.Utc),
                            Designation = "reptilian",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 144, DateTimeKind.Utc),
                            EyeColors = "black",
                            HairColors = "n/a",
                            Homeworld = "https://swapi.dev/api/planets/23/",
                            Language = "Galatic Basic",
                            Name = "Rodian",
                            SkinColors = "green, blue",
                            SpecieId = 4,
                            Url = "https://swapi.dev/api/species/4/"
                        },
                        new
                        {
                            Id = new Guid("aed3f0c1-b178-435b-9656-f65c6f2756a9"),
                            AverageHeight = "300",
                            AverageLifespan = "1000",
                            Created = new DateTime(2014, 12, 10, 17, 12, 50, 410, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 146, DateTimeKind.Utc),
                            EyeColors = "yellow, red",
                            HairColors = "n/a",
                            Homeworld = "https://swapi.dev/api/planets/24/",
                            Language = "Huttese",
                            Name = "Hutt",
                            SkinColors = "green, brown, tan",
                            SpecieId = 5,
                            Url = "https://swapi.dev/api/species/5/"
                        },
                        new
                        {
                            Id = new Guid("1abcf174-225b-4cc9-94f7-1d00f00c26e3"),
                            AverageHeight = "66",
                            AverageLifespan = "900",
                            Created = new DateTime(2014, 12, 15, 12, 27, 22, 877, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 148, DateTimeKind.Utc),
                            EyeColors = "brown, green, yellow",
                            HairColors = "brown, white",
                            Homeworld = "https://swapi.dev/api/planets/28/",
                            Language = "Galactic basic",
                            Name = "Yoda's species",
                            SkinColors = "green, yellow",
                            SpecieId = 6,
                            Url = "https://swapi.dev/api/species/6/"
                        },
                        new
                        {
                            Id = new Guid("8f552b7b-c3ab-4b5c-b70d-fad1bb40f945"),
                            AverageHeight = "200",
                            AverageLifespan = "unknown",
                            Created = new DateTime(2014, 12, 15, 13, 7, 47, 704, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 151, DateTimeKind.Utc),
                            EyeColors = "yellow, orange",
                            HairColors = "none",
                            Homeworld = "https://swapi.dev/api/planets/29/",
                            Language = "Dosh",
                            Name = "Trandoshan",
                            SkinColors = "brown, green",
                            SpecieId = 7,
                            Url = "https://swapi.dev/api/species/7/"
                        },
                        new
                        {
                            Id = new Guid("acfb00ac-3e4b-4056-b313-de589f619bfa"),
                            AverageHeight = "160",
                            AverageLifespan = "unknown",
                            Created = new DateTime(2014, 12, 18, 11, 9, 52, 263, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 153, DateTimeKind.Utc),
                            EyeColors = "yellow",
                            HairColors = "none",
                            Homeworld = "https://swapi.dev/api/planets/31/",
                            Language = "Mon Calamarian",
                            Name = "Mon Calamari",
                            SkinColors = "red, blue, brown, magenta",
                            SpecieId = 8,
                            Url = "https://swapi.dev/api/species/8/"
                        },
                        new
                        {
                            Id = new Guid("79f5566d-3cd9-4fd7-92dd-41ec5f95bef1"),
                            AverageHeight = "100",
                            AverageLifespan = "unknown",
                            Created = new DateTime(2014, 12, 18, 11, 22, 0, 285, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 155, DateTimeKind.Utc),
                            EyeColors = "orange, brown",
                            HairColors = "white, brown, black",
                            Homeworld = "https://swapi.dev/api/planets/7/",
                            Language = "Ewokese",
                            Name = "Ewok",
                            SkinColors = "brown",
                            SpecieId = 9,
                            Url = "https://swapi.dev/api/species/9/"
                        },
                        new
                        {
                            Id = new Guid("a88f335c-7a68-4b90-9978-3752137603ad"),
                            AverageHeight = "180",
                            AverageLifespan = "unknown",
                            Created = new DateTime(2014, 12, 18, 11, 26, 20, 103, DateTimeKind.Utc),
                            Designation = "sentient",
                            Edited = new DateTime(2014, 12, 20, 21, 36, 42, 157, DateTimeKind.Utc),
                            EyeColors = "black",
                            HairColors = "none",
                            Homeworld = "https://swapi.dev/api/planets/33/",
                            Language = "Sullutese",
                            Name = "Sullustan",
                            SkinColors = "pale",
                            SpecieId = 10,
                            Url = "https://swapi.dev/api/species/10/"
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.Starship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumables")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crew")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("MGLT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Passengers")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("TEXT");

                    b.Property<int>("StarshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Starships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1bd0355-d501-424b-b67f-b6bac57d5898"),
                            CargoCapacity = "3000000",
                            Consumables = "1 year",
                            CostInCredits = "3500000",
                            Created = new DateTime(2014, 12, 10, 14, 20, 33, 369, DateTimeKind.Utc),
                            Crew = "30-165",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 867, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Length = "150",
                            MGLT = "60",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "950",
                            Model = "CR90 corvette",
                            Name = "CR90 corvette",
                            Passengers = "600",
                            StarshipClass = "corvette",
                            StarshipId = 2,
                            Url = "https://swapi.dev/api/starships/2/"
                        },
                        new
                        {
                            Id = new Guid("ae9f1917-adf1-45c1-a5ba-8c13679512ec"),
                            CargoCapacity = "36000000",
                            Consumables = "2 years",
                            CostInCredits = "150000000",
                            Created = new DateTime(2014, 12, 10, 15, 8, 19, 848, DateTimeKind.Utc),
                            Crew = "47,060",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 870, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Length = "1,600",
                            MGLT = "60",
                            Manufacturer = "Kuat Drive Yards",
                            MaxAtmospheringSpeed = "975",
                            Model = "Imperial I-class Star Destroyer",
                            Name = "Star Destroyer",
                            Passengers = "n/a",
                            StarshipClass = "Star Destroyer",
                            StarshipId = 3,
                            Url = "https://swapi.dev/api/starships/3/"
                        },
                        new
                        {
                            Id = new Guid("cca376fc-13fa-485c-8199-e3118efaaac7"),
                            CargoCapacity = "180000",
                            Consumables = "1 month",
                            CostInCredits = "240000",
                            Created = new DateTime(2014, 12, 10, 15, 48, 0, 586, DateTimeKind.Utc),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 873, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Length = "38",
                            MGLT = "70",
                            Manufacturer = "Sienar Fleet Systems, Cyngus Spaceworks",
                            MaxAtmospheringSpeed = "1000",
                            Model = "Sentinel-class landing craft",
                            Name = "Sentinel-class landing craft",
                            Passengers = "75",
                            StarshipClass = "landing craft",
                            StarshipId = 5,
                            Url = "https://swapi.dev/api/starships/5/"
                        },
                        new
                        {
                            Id = new Guid("4b753e1c-d3fa-48a3-bda9-08637b82ece1"),
                            CargoCapacity = "1000000000000",
                            Consumables = "3 years",
                            CostInCredits = "1000000000000",
                            Created = new DateTime(2014, 12, 10, 16, 36, 50, 509, DateTimeKind.Utc),
                            Crew = "342,953",
                            Edited = new DateTime(2014, 12, 20, 21, 26, 24, 783, DateTimeKind.Utc),
                            HyperdriveRating = "4.0",
                            Length = "120000",
                            MGLT = "10",
                            Manufacturer = "Imperial Department of Military Research, Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "DS-1 Orbital Battle Station",
                            Name = "Death Star",
                            Passengers = "843,342",
                            StarshipClass = "Deep Space Mobile Battlestation",
                            StarshipId = 9,
                            Url = "https://swapi.dev/api/starships/9/"
                        },
                        new
                        {
                            Id = new Guid("c12fddc7-b974-4a86-bf6f-234bc31c2d96"),
                            CargoCapacity = "100000",
                            Consumables = "2 months",
                            CostInCredits = "100000",
                            Created = new DateTime(2014, 12, 10, 16, 59, 45, 94, DateTimeKind.Utc),
                            Crew = "4",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 880, DateTimeKind.Utc),
                            HyperdriveRating = "0.5",
                            Length = "34.37",
                            MGLT = "75",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "YT-1300 light freighter",
                            Name = "Millennium Falcon",
                            Passengers = "6",
                            StarshipClass = "Light freighter",
                            StarshipId = 10,
                            Url = "https://swapi.dev/api/starships/10/"
                        },
                        new
                        {
                            Id = new Guid("7b251f1e-c565-4483-9db4-91ad118ab727"),
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "134999",
                            Created = new DateTime(2014, 12, 12, 11, 0, 39, 817, DateTimeKind.Utc),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 883, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Length = "14",
                            MGLT = "80",
                            Manufacturer = "Koensayr Manufacturing",
                            MaxAtmospheringSpeed = "1000km",
                            Model = "BTL Y-wing",
                            Name = "Y-wing",
                            Passengers = "0",
                            StarshipClass = "assault starfighter",
                            StarshipId = 11,
                            Url = "https://swapi.dev/api/starships/11/"
                        },
                        new
                        {
                            Id = new Guid("d5564327-00b2-4bdf-a2ea-baed1ddb382c"),
                            CargoCapacity = "110",
                            Consumables = "1 week",
                            CostInCredits = "149999",
                            Created = new DateTime(2014, 12, 12, 11, 19, 5, 340, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 886, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Length = "12.5",
                            MGLT = "100",
                            Manufacturer = "Incom Corporation",
                            MaxAtmospheringSpeed = "1050",
                            Model = "T-65 X-wing",
                            Name = "X-wing",
                            Passengers = "0",
                            StarshipClass = "Starfighter",
                            StarshipId = 12,
                            Url = "https://swapi.dev/api/starships/12/"
                        },
                        new
                        {
                            Id = new Guid("c3cd8690-b649-40d4-8fba-469cda2628e0"),
                            CargoCapacity = "150",
                            Consumables = "5 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 12, 11, 21, 32, 991, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 889, DateTimeKind.Utc),
                            HyperdriveRating = "1.0",
                            Length = "9.2",
                            MGLT = "105",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "1200",
                            Model = "Twin Ion Engine Advanced x1",
                            Name = "TIE Advanced x1",
                            Passengers = "0",
                            StarshipClass = "Starfighter",
                            StarshipId = 13,
                            Url = "https://swapi.dev/api/starships/13/"
                        },
                        new
                        {
                            Id = new Guid("a37a5f5b-8996-4532-a85a-56714d57e7a8"),
                            CargoCapacity = "250000000",
                            Consumables = "6 years",
                            CostInCredits = "1143350000",
                            Created = new DateTime(2014, 12, 15, 12, 31, 42, 547, DateTimeKind.Utc),
                            Crew = "279,144",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 893, DateTimeKind.Utc),
                            HyperdriveRating = "2.0",
                            Length = "19000",
                            MGLT = "40",
                            Manufacturer = "Kuat Drive Yards, Fondor Shipyards",
                            MaxAtmospheringSpeed = "n/a",
                            Model = "Executor-class star dreadnought",
                            Name = "Executor",
                            Passengers = "38000",
                            StarshipClass = "Star dreadnought",
                            StarshipId = 15,
                            Url = "https://swapi.dev/api/starships/15/"
                        },
                        new
                        {
                            Id = new Guid("8c2f9aed-020b-41de-b1cc-2c68720e1b06"),
                            CargoCapacity = "19000000",
                            Consumables = "6 months",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 34, 52, 264, DateTimeKind.Utc),
                            Crew = "6",
                            Edited = new DateTime(2014, 12, 20, 21, 23, 49, 895, DateTimeKind.Utc),
                            HyperdriveRating = "4.0",
                            Length = "90",
                            MGLT = "20",
                            Manufacturer = "Gallofree Yards, Inc.",
                            MaxAtmospheringSpeed = "650",
                            Model = "GR-75 medium transport",
                            Name = "Rebel transport",
                            Passengers = "90",
                            StarshipClass = "Medium transport",
                            StarshipId = 17,
                            Url = "https://swapi.dev/api/starships/17/"
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumables")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crew")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Passengers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleClass")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa0075ee-d0e2-4112-afdb-31f419aa8104"),
                            CargoCapacity = "50000",
                            Consumables = "2 months",
                            CostInCredits = "150000",
                            Created = new DateTime(2014, 12, 10, 15, 36, 25, 724, DateTimeKind.Utc),
                            Crew = "46",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 661, DateTimeKind.Utc),
                            Length = "36.8 ",
                            Manufacturer = "Corellia Mining Corporation",
                            MaxAtmospheringSpeed = "30",
                            Model = "Digger Crawler",
                            Name = "Sand Crawler",
                            Passengers = "30",
                            Url = "https://swapi.dev/api/vehicles/4/",
                            VehicleClass = "wheeled",
                            VehicleId = 4
                        },
                        new
                        {
                            Id = new Guid("44eac0e1-abee-4ed0-99d0-063a11dffb6a"),
                            CargoCapacity = "50",
                            Consumables = "0",
                            CostInCredits = "14500",
                            Created = new DateTime(2014, 12, 10, 16, 1, 52, 434, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 665, DateTimeKind.Utc),
                            Length = "10.4 ",
                            Manufacturer = "Incom Corporation",
                            MaxAtmospheringSpeed = "1200",
                            Model = "T-16 skyhopper",
                            Name = "T-16 skyhopper",
                            Passengers = "1",
                            Url = "https://swapi.dev/api/vehicles/6/",
                            VehicleClass = "repulsorcraft",
                            VehicleId = 6
                        },
                        new
                        {
                            Id = new Guid("c70bb224-ad6b-4e32-946d-c5e2c356c6b7"),
                            CargoCapacity = "5",
                            Consumables = "unknown",
                            CostInCredits = "10550",
                            Created = new DateTime(2014, 12, 10, 16, 13, 52, 586, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 668, DateTimeKind.Utc),
                            Length = "3.4 ",
                            Manufacturer = "SoroSuub Corporation",
                            MaxAtmospheringSpeed = "250",
                            Model = "X-34 landspeeder",
                            Name = "X-34 landspeeder",
                            Passengers = "1",
                            Url = "https://swapi.dev/api/vehicles/7/",
                            VehicleClass = "repulsorcraft",
                            VehicleId = 7
                        },
                        new
                        {
                            Id = new Guid("f2bf8936-0c3e-4592-ba31-2a334d905477"),
                            CargoCapacity = "65",
                            Consumables = "2 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 10, 16, 33, 52, 860, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 670, DateTimeKind.Utc),
                            Length = "6.4",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "1200",
                            Model = "Twin Ion Engine/Ln Starfighter",
                            Name = "TIE/LN starfighter",
                            Passengers = "0",
                            Url = "https://swapi.dev/api/vehicles/8/",
                            VehicleClass = "starfighter",
                            VehicleId = 8
                        },
                        new
                        {
                            Id = new Guid("ecfa9a40-a1ab-466b-88a0-ad671a4e30fe"),
                            CargoCapacity = "10",
                            Consumables = "none",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 22, 12, 0, DateTimeKind.Utc),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 672, DateTimeKind.Utc),
                            Length = "4.5",
                            Manufacturer = "Incom corporation",
                            MaxAtmospheringSpeed = "650",
                            Model = "t-47 airspeeder",
                            Name = "Snowspeeder",
                            Passengers = "0",
                            Url = "https://swapi.dev/api/vehicles/14/",
                            VehicleClass = "airspeeder",
                            VehicleId = 14
                        },
                        new
                        {
                            Id = new Guid("f9eb7ff5-9812-4ab2-8b7a-b938dcedbe06"),
                            CargoCapacity = "none",
                            Consumables = "2 days",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 33, 15, 838, DateTimeKind.Utc),
                            Crew = "1",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 675, DateTimeKind.Utc),
                            Length = "7.8",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxAtmospheringSpeed = "850",
                            Model = "TIE/sa bomber",
                            Name = "TIE bomber",
                            Passengers = "0",
                            Url = "https://swapi.dev/api/vehicles/16/",
                            VehicleClass = "space/planetary bomber",
                            VehicleId = 16
                        },
                        new
                        {
                            Id = new Guid("656abdfc-2a3f-47f4-9913-2a644ab51d3d"),
                            CargoCapacity = "1000",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 38, 25, 937, DateTimeKind.Utc),
                            Crew = "5",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 677, DateTimeKind.Utc),
                            Length = "20",
                            Manufacturer = "Kuat Drive Yards, Imperial Department of Military Research",
                            MaxAtmospheringSpeed = "60",
                            Model = "All Terrain Armored Transport",
                            Name = "AT-AT",
                            Passengers = "40",
                            Url = "https://swapi.dev/api/vehicles/18/",
                            VehicleClass = "assault walker",
                            VehicleId = 18
                        },
                        new
                        {
                            Id = new Guid("000af4e1-2dba-437c-acc6-b1cf803bcc0a"),
                            CargoCapacity = "200",
                            Consumables = "none",
                            CostInCredits = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 46, 42, 384, DateTimeKind.Utc),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 679, DateTimeKind.Utc),
                            Length = "2",
                            Manufacturer = "Kuat Drive Yards, Imperial Department of Military Research",
                            MaxAtmospheringSpeed = "90",
                            Model = "All Terrain Scout Transport",
                            Name = "AT-ST",
                            Passengers = "0",
                            Url = "https://swapi.dev/api/vehicles/19/",
                            VehicleClass = "walker",
                            VehicleId = 19
                        },
                        new
                        {
                            Id = new Guid("4467ae42-965a-43d9-95a9-f90d03151b5d"),
                            CargoCapacity = "10",
                            Consumables = "1 day",
                            CostInCredits = "75000",
                            Created = new DateTime(2014, 12, 15, 12, 58, 50, 530, DateTimeKind.Utc),
                            Crew = "2",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 681, DateTimeKind.Utc),
                            Length = "7",
                            Manufacturer = "Bespin Motors",
                            MaxAtmospheringSpeed = "1500",
                            Model = "Storm IV Twin-Pod",
                            Name = "Storm IV Twin-Pod cloud car",
                            Passengers = "0",
                            Url = "https://swapi.dev/api/vehicles/20/",
                            VehicleClass = "repulsorcraft",
                            VehicleId = 20
                        },
                        new
                        {
                            Id = new Guid("d02f4743-5140-466e-a27f-6bec3a005474"),
                            CargoCapacity = "2000000",
                            Consumables = "Live food tanks",
                            CostInCredits = "285000",
                            Created = new DateTime(2014, 12, 18, 10, 44, 14, 217, DateTimeKind.Utc),
                            Crew = "26",
                            Edited = new DateTime(2014, 12, 20, 21, 30, 21, 684, DateTimeKind.Utc),
                            Length = "30",
                            Manufacturer = "Ubrikkian Industries Custom Vehicle Division",
                            MaxAtmospheringSpeed = "100",
                            Model = "Modified Luxury Sail Barge",
                            Name = "Sail barge",
                            Passengers = "500",
                            Url = "https://swapi.dev/api/vehicles/24/",
                            VehicleClass = "sail barge",
                            VehicleId = 24
                        });
                });

            modelBuilder.Entity("APIStarWar.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });
#pragma warning restore 612, 618
        }
    }
}
